Liuggio\HelpDeskBundle\Entity\TicketState:
  type: entity
  table: ticket__state
  fields:
    id:
      type: integer
      id: true
      generator:
        strategy: AUTO
    code:
      type: string
      length: '7'
    description:
      type: string
      length: 255
    weight:
      type: integer
  indexes:
    code_index:
      columns: [ code ]
  lifecycleCallbacks: {  }
