LiuggioHelpDeskTicketSystemBundle_customer_care_ticket:
    resource: "@LiuggioHelpDeskTicketSystemBundle/Resources/config/routing/ticket.yml"
    prefix:   /customer-care/ticket


LiuggioHelpDeskTicketSystemBundle_customer_care_coment:
    resource: "@LiuggioHelpDeskTicketSystemBundle/Resources/config/routing/comment.yml"
    prefix:   /customer-care/comment